#!/bin/sh
###############################################################################
##
## vadduser - 1.5
##
## Chris Johnson, Jan 1998
##
###############################################################################
trap "" 1 2 3 15

POPUSER=`echo $1 | cut -d@ -f1`
echo $1 | grep '\@' > /dev/null 2>&1
if [ $? -eq 0 ]
then
	HOST=`echo $1 | cut -d@ -f2`
else
	HOST='';
fi

POPACCT=vpopmail
POPGRP=popusers

grep "^${POPACCT}\:" /etc/passwd > /dev/null 2>&1
if [ $? -ne 0 ]
then
	echo "Cannot find master POP user $POPACCT in /etc/passwd"
	exit 
else
	POPHOME=`grep "^${POPACCT}\:" /etc/passwd | cut -d: -f6`
	if [ "x$HOST" = "x" ]
	then
		PASSWD="$POPHOME/vpasswd"
		PBAK="$POPHOME/vpasswd-"
		PLOCK="$POPHOME/.pwd.lock"
		HOMEDIR="$POPHOME/users"
	else
		PASSWD="$POPHOME/domains/$HOST/vpasswd"
		PBAK="$POPHOME/domains/$HOST/vpasswd-"
		PLOCK="$POPHOME/domains/$HOST/.pwd.lock"
		HOMEDIR="$POPHOME/domains/$HOST"
	fi
fi

which vmkpasswd > /dev/null 2>&1
if [ $? -eq 1 ]
then
	echo "Yikes! Cant find vmkpasswd - needed to make encrypted password"
	echo "Aborting!!"
	exit
fi

if [ x`whoami` != xroot ]; then
	echo "You should be root to run this!!"
	exit 1
fi

if [ $# -eq 0 ]
then
	echo "Syntax: `basename $0` <POP User>"
	echo ""
	echo "    Note: The pop directory is _relative_ to the home directory"
	echo "          of the POP master user."
	echo ""
	exit
fi

if [ ! -d $HOMEDIR ]
then
	echo "Directory $HOMEDIR dosent exist."
	echo "Aborting"
	exit
fi
	

grep "^${POPUSER}\:" $PASSWD > /dev/null 2>&1
if [ $? -eq 0 ]
then
	echo "The login $POPUSER already exists."
	exit 1
fi

if [ -f $PLOCK ]; then
	echo "$PASSWD is locked - someone else adding users to the"
	echo "POP system? If you are *sure* this is an error, then delete"
	echo "the file $PLOCK"
	exit 1
fi
touch $PLOCK

echo ""
echo "Adding POP user $POPUSER..."

PW=""
while [ "x$PW" = "x" ]
do
	PW=`vmkpasswd`
done

echo "    Putting entry into vpasswd..."
cp $PASSWD $PBAK
echo "$POPUSER:$PW:::POP User:$HOMEDIR/$POPUSER:NOLOGIN" >> $PASSWD
chmod 644 $PASSWD

rm -f $PLOCK

echo "    Creating $HOMEDIR/$POPUSER..."
mkdir $HOMEDIR/$POPUSER
chmod 700 $HOMEDIR/$POPUSER
echo "    Creating Maildir..."
/var/qmail/bin/maildirmake $HOMEDIR/$POPUSER/Maildir
chown -R $POPACCT $HOMEDIR/$POPUSER
chgrp -R $POPGRP $HOMEDIR/$POPUSER

echo "Okay - added $1 to POP system"
