$Id: README.CGI,v 1.1 1998/06/16 21:18:03 chris Exp $
-------------------------------------------------------------------------------

Vchkpw CGI
==========
Chris Johnson, Copyright (C) April 1998
Email: sixie@nccnet.co.uk

This is licensed under the terms of the General Public License. See the file
LICENSE for more details.

This CGI allows an administrator of a virtual domain to add and delete users,
and also to change user passwords. It is designed to run with vchkpw, which
should have come in the same package.

You will need Perl 5 to be able to run the CGI.

See the file doc/INSTALL.CGI for installation instructions.

Please send bug reports to: sixie@nccnet.co.uk

-------------------------------------------------------------------------------
